import { promises as fs } from 'node:fs';
import path from 'node:path';
import type { LogEntry } from '../types.js';
import { isDateKey, toDateKey } from '../utils.js';

export interface FileStoreOptions {
  dir: string;
  /** Default `log`. */
  extension?: string;
  /** Default `true`. */
  gitignore?: boolean;
}

const GITIGNORE_CONTENT = '# Generated by node-log-viewer. Log files must never be committed.\n*\n!.gitignore\n';

/**
 * Appends JSON-lines entries to one file per day (`YYYY-MM-DD.log`).
 * Writes are serialized through an internal queue so ordering is preserved
 * and concurrent appends never interleave.
 */
export class FileStore {
  readonly dir: string;
  readonly extension: string;
  private readonly gitignore: boolean;
  private ready: Promise<void> | null = null;
  private queue: Promise<void> = Promise.resolve();
  private pending = 0;

  constructor(options: FileStoreOptions) {
    this.dir = path.resolve(options.dir);
    this.extension = (options.extension ?? 'log').replace(/^\./, '');
    this.gitignore = options.gitignore ?? true;
  }

  /** Ensures the directory (and its .gitignore) exist. Idempotent. */
  init(): Promise<void> {
    if (!this.ready) {
      this.ready = (async () => {
        await fs.mkdir(this.dir, { recursive: true });
        if (this.gitignore) {
          const target = path.join(this.dir, '.gitignore');
          try {
            await fs.access(target);
          } catch {
            await fs.writeFile(target, GITIGNORE_CONTENT, 'utf8');
          }
        }
      })().catch((err) => {
        this.ready = null;
        throw err;
      });
    }
    return this.ready;
  }

  fileFor(date: string): string {
    return path.join(this.dir, `${date}.${this.extension}`);
  }

  dateFromFile(file: string): string | null {
    const base = path.basename(file);
    const suffix = `.${this.extension}`;
    if (!base.endsWith(suffix)) return null;
    const date = base.slice(0, -suffix.length);
    return isDateKey(date) ? date : null;
  }

  /** Queues an append. Resolves once the line is on disk. */
  append(entry: LogEntry): Promise<void> {
    const date = toDateKey(new Date(entry.ts));
    const line = `${JSON.stringify(entry)}\n`;
    this.pending += 1;
    const op = this.queue
      .then(() => this.init())
      .then(() => fs.appendFile(this.fileFor(date), line, 'utf8'))
      .finally(() => {
        this.pending -= 1;
      });
    // keep the chain alive even if a write fails
    this.queue = op.catch(() => undefined);
    return op;
  }

  /** Resolves once the directory is initialised and every queued write has completed. */
  async flush(): Promise<void> {
    await this.init().catch(() => undefined);
    while (this.pending > 0) {
      await this.queue;
    }
  }

  /** Lists available dates, newest first. */
  async listDates(): Promise<string[]> {
    await this.init();
    const names = await fs.readdir(this.dir);
    const dates = names.map((n) => this.dateFromFile(n)).filter((d): d is string => d !== null);
    return dates.sort((a, b) => (a < b ? 1 : a > b ? -1 : 0));
  }

  async readRaw(date: string): Promise<string> {
    if (!isDateKey(date)) throw new Error(`Invalid date key: ${date}`);
    try {
      return await fs.readFile(this.fileFor(date), 'utf8');
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') return '';
      throw err;
    }
  }

  async stat(date: string): Promise<{ sizeBytes: number; modifiedAt: string } | null> {
    if (!isDateKey(date)) return null;
    try {
      const s = await fs.stat(this.fileFor(date));
      return { sizeBytes: s.size, modifiedAt: s.mtime.toISOString() };
    } catch {
      return null;
    }
  }

  async delete(date: string): Promise<boolean> {
    if (!isDateKey(date)) throw new Error(`Invalid date key: ${date}`);
    await this.flush();
    try {
      await fs.unlink(this.fileFor(date));
      return true;
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') return false;
      throw err;
    }
  }

  /** Truncates a day's file (keeps the file, removes all entries). */
  async clear(date: string): Promise<void> {
    if (!isDateKey(date)) throw new Error(`Invalid date key: ${date}`);
    await this.flush();
    await this.init();
    await fs.writeFile(this.fileFor(date), '', 'utf8');
  }
}
